### PR TITLE
Update package.json to depend on latest passport-oauth version

### PR DESCRIPTION
**Pull request by mcudich**

### CODE REVIEW

**Comment by florianheinemann** [comment]
Hi! Thanks. I have nothing to test this change against but from what I gathered from the comments this change is needed. Did you test it locally and did it work?

Florian

**Comment by mcudich** [comment]
Yep - it works great!

**Comment by florianheinemann** [comment]
Thanks!

**Comment by florianheinemann** [comment]
Published as passport-dropbox-oauth2@1.0.0

**Pull request merged**
